### ISSUE TITLE
Epic 1 - Testing/Documentation

### ISSUE THREAD

**Issue by 0xjei** [quadratic-funding/mpc-phase2-suite#176]
__Description__
This epic concerns everything related to Testing and Documentation activities.

__Milestones__
- [ ] MS1 - Testing <Bootstrap>
- [ ] MS2 - Testing <Unit Testing>
- [ ] MS3 - Testing <E2E, Pentesting, ...>
- [ ] MS4 - Documentation <Bootstrap>
- [ ] MS5 - Documentation <Writing>
- [ ] MS6 - Documentation <Finalization>
