### ISSUE TITLE
MPC Phase 2 Suite PoC (Alpha Release)

### ISSUE THREAD

**Issue by 0xjei** [quadratic-funding/mpc-phase2-suite#6]
[mpc-phase2-suite](https://github.com/Jeeiii/mpc-phase2-suite) PoC (Alpha Release).
   
- [x] quadratic-funding/mpc-phase2-suite#20 
- [x] quadratic-funding/mpc-phase2-suite#21 
- [x] quadratic-funding/mpc-phase2-suite#22 
- [x] quadratic-funding/mpc-phase2-suite#23
- [x] quadratic-funding/mpc-phase2-suite#1 
- [x] quadratic-funding/mpc-phase2-suite#3 
- [x] #24 
- [x] #25 
- [x] #26 
- [x] #27 
- [x] #29 
- [x] #4 
- [x] #2 
- [x] #5 
- [x] #30 (small only)

__What's missing after testing?__
- [x] Fix waiting queue bug (do not pass the baton when next party is in "WAITING" status)
- [x] Improve coordination automation
- [x] Add automatic GH GIST publication
- [x] Add CLI listener for circuit waiting queue
